--COMANDOS DE CRIAÇÃO, ALTERAÇÃO E EXCLUSÃO DE OBJETOS

--CRIAR TABELA
CREATE TABLE T_TESTE_DDL
( --Chave do sql é parentêses
    id_teste NUMBER (10) NOT NULL, -- Criando um campo numérico de tamangho 10 obrigatório
    nm_teste VARCHAR2 (15) NOT NULL, -- Criando um campo texto de tamanho 15 obrigatório
    ds_teste VARCHAR2 (100) NULL -- Criando um campo de texto de tamanho 100 opcional
); -- Ao fechar chave (parentêsis), sempre finaliza com ponto e vírgula, enquanto dentro da chave finaliza com vírgula (menos na última linha)

--EXCLUIR TABELA
--Há três formas, é preciso escolher apenas uma para sua exclusão 
DROP TABLE T_TESTE_DDL; --Excluindo apenas a tabela
DROP TABLE T_TESTE_DDL CASCADE CONSTRAINTS; --Excluindo a tabela e todas os seus relacionamentos
DROP TABLE T_TESTE_DDL CASCADE CONSTRAINTS PURGE; --Excluindo a tabela, seus relacionamentos e esvaziando a lixeira (não há a possibilidade de recuperar)

--ALTERAR TABELA
--NOME DA TABELA
ALTER TABLE T_TESTE_DDL RENAME TO T_TESTE_DDL_2024;
ALTER TABLE T_TESTE_DDL_2024 RENAME TO T_TESTE_DDL;

--CRIAR CHAVE PRIMÁRIA
ALTER TABLE T_TESTE_DDL ADD CONSTRAINT PK_TESTE_DDL PRIMARY KEY (id_teste);

--CRIAR REGRA (CONSTRAINT) DE NOME QUE NÃO REPETE
ALTER TABLE T_TESTE_DDL ADD CONSTRAINT UN_TESTE_DDL_NOME UNIQUE (nm_teste);

--ADICIONAR UMA COLUNA
ALTER TABLE T_TESTE_DDL ADD DC_EMAIL VARCHAR2 (100);

--ADICIONAR DUAS COLUNAS
ALTER TABLE T_TESTE_DDL ADD (DS_OBS1 VARCHAR2(100) NOT NULL, DS_OBS2 VARCHAR(100));

--VISUALIZAÇÃO DA ESTRUTURA DA TABELA
DESC T_TESTE_DDL;

--EXISTEM TABELAS INTERNAS NO ORACLE COM AS ESTRUTURAS DAS TABELAS
--TABELAS DE TABELAS (USER_TABLES)
--NELAS PODEMOS VER TUDO DE UMA TABELA
--COMO POR EXEMPLO: ATRIBUTOS FÍSICOS E SE ELA TEM CONSTRAINTS
SELECT * FROM USER_TABLES WHERE TABLE_NAME = 'T_TABLE_DDL';
SELECT * FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'T_TESTES_DDL';
--NA TABELA USER_CONS_COLUMS QUE VEMOS SE TEM PRIMARY KEY
SELECT * FROM USER_CONS_COLUMNS WHERE TABLE_NAME = 'T_TESTES_DDL';

DESC USER_TABLES;

--MODIFICAR ESPECIFICAÇÕES DE UM CAMPO DA TABELA
ALTER TABLE T_TESTE_DDL MODIFY DS_OBS2 VARCHAR2(50) NOT NULL;

--ADICIONAR CAMPO DATA
--CAMPO DEFAULT
ALTER TABLE T_TESTE_DDL ADD DT_TESTE_DDL DATE DEFAULT SYSDATE;

--RENOMEANDO CAMPOS
ALTER TABLE T_TESTE_DDL RENAME COLUMN DS_OBS1 TO DS_OBS3;

--COMENTÁRIOS NA TABELA
COMMENT ON TABLE T_TESTE_DDL IS 'Teste de tabela para comandos de estrutura DDL';

--REMOVENDO CAMPOS
ALTER TABLE T_TESTE_DDL DROP COLUMN DS_OBS2; --Para coluna específica
ALTER TABLE T_TESTE_DDL DROP (DS_OBS3, DT_TESTE_DDL);
DESC T_TESTE_DDL;




--POPULAR DADOS
-- O COMANDO INSERT INSERE DADOS NA TABELA
INSERT INTO T_TESTE_DDL (
    id_teste,
    nm_teste,
    ds_teste,
    ds_email
)

VALUES (
    1,
    'TESTE NUMERO 1',
    'DESCRITIVO DE TESTE 1',
    'EMAIL DE TESTE 1'
);

--CONSULTA 
SELECT * FROM T_TESTE_DDL;

COMMIT;

--OS CAMPOS DS_TESTE E DS_EMAIL NÃO SÃO OBRIGATÓRIOS
--SE QUISER INSERIR MAIS REGISTROS COM OS DADOS 'Teste 2' e 'Descrição 2'

--RETIRA OS VALORES DO INSERT INTO E TROCOU OS VALORES DE 1 PARA 2 

INSERT INTO T_TESTE_DDL (
    id_teste,
    nm_teste
)

VALUES (
    2,
    'TESTE NUMERO 2'
);
COMMIT;

SELECT * FROM T_TESTE_DDL;


